### PR TITLE
fix(mux): fix edge pane detection logic for tmux (#118)

### LINKED ISSUE #118: [Bug]: Navigation via tmux not working after tmux pane resized
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Multiplexer Integration

tmux

### Multiplexer Version

tmux 3.3a

### Steps to Reproduce

1. Open terminal
2. New tmux session
3. Create a split
4. Try to navigate (should work) (both direction works nvim <-> terminal)
5. Maximize or fullscreen the terminal
6. Navigation from nvim -> terminal no longer works. (Terminal -> nvim still works)

### Expected Behavior

Navigation should work even when maximize/fullscreen terminal.

### Actual Behavior

Navigation from nvim -> terminal not working in maximize/fullscreen terminal.

### Minimal Configuration to Reproduce

```lua
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- do not remove the colorscheme! it makes testing nicer
  'folke/tokyonight.nvim',
  'mrjones2014/smart-splits.nvim',
  -- add any other pugins here
}

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

require('smart-splits').setup({
  -- add any options here
})

-- recommended mappings
-- resizing splits
-- these keymaps will also accept a range,
-- for example `10<A-h>` will `resize_left` by `(10 * config.default_amount)`
vim.keymap.set('n', '<A-h>', require('smart-splits').resize_left)
vim.keymap.set('n', '<A-j>', require('smart-splits').resize_down)
vim.keymap.set('n', '<A-k>', require('smart-splits').resize_up)
vim.keymap.set('n', '<A-l>', require('smart-splits').resize_right)
-- moving between splits
vim.keymap.set('n', '<C-h>', require('smart-splits').move_cursor_left)
vim.keymap.set('n', '<C-j>', require('smart-splits').move_cursor_down)
vim.keymap.set('n', '<C-k>', require('smart-splits').move_cursor_up)
vim.keymap.set('n', '<C-l>', require('smart-splits').move_cursor_right)
-- swapping buffers between windows
vim.keymap.set('n', '<leader><leader>h', require('smart-splits').swap_buf_left)
vim.keymap.set('n', '<leader><leader>j', require('smart-splits').swap_buf_down)
vim.keymap.set('n', '<leader><leader>k', require('smart-splits').swap_buf_up)
vim.keymap.set('n', '<leader><leader>l', require('smart-splits').swap_buf_right)

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme! it makes testing nicer
vim.cmd([[colorscheme tokyonight]])
```

### Additional Details and/or Screenshots

My nvim dotfiles: https://github.com/icyrainz/.dotfiles/tree/master/nvim

### PR DESCRIPTION
**Pull request by freddiehaddad**
Fixes #118

### CODE REVIEW

File: lua/smart-splits/mux/tmux.lua [hunk 1]
```diff
@@ -44,65 +44,27 @@ function M.current_pane_at_edge(direction)
...
-    local expr = string.format('return %s %s %s', tonumber(active_pane_coord), op, tonumber(top_coord))
-    return loadstring(expr)()
-  end)
-
-  if not ok then
-    return false
-  else
-    return value
-  end
+  return false
```
Comment (mrjones2014) [inline lua/smart-splits/mux/tmux.lua:67]: instead of `if cond then return true else return false end` let's just `return cond`, i.e. `return type(result) == 'table' and #result == 1`

**Comment by mrjones2014** [comment]
Wow, this seems much simpler! Thanks for the PR! I'll wait for @icyrainz to confirm this fixes the issue for him as well before merging.

**Comment by mrjones2014** [comment]
We're also getting `lua/smart-splits/mux/tmux.lua:3:7: unused variable AtEdgeBehavior` in CI now. Since its unused now, you can just delete the line.

**Review by mrjones2014 — APPROVED** [review]
