### PR TITLE
fix(mux): get tmux pane running vim instead of active pane

### LINKED ISSUE #249: [Bug]: @pane-is-vim not behaving correctly with resurrect plugin
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713773202

### Multiplexer Integration

tmux

### Multiplexer Version

tmux 3.4

### Steps to Reproduce

1. Install resurrect plugin
2. Open two tmux panes, one with Neovim and one with a shell
3. Save the session using resurrect
4. Restart tmux (`tmux kill-server` and then start again with any method)
5. Enter the session with two panes open.
6. Observe the shell acting as if `@pane-is-vim` is set

### Expected Behavior

The shell should act as if `@pane-is-set` is off even after restoration.

### Actual Behavior

The shell acts as if `@pane-is-vim` is set

### Minimal Configuration to Reproduce

I use NixVim. When Nix is installed, it can be run as standalone with: `nix run 'github:Mikilio/neovix`
The resulting executable is a shell script that starts the program with the correct environment and config. The `ini.nvim` can be found by examining that. (Or I can provide it)
But it is actually a very standard configuration.

More important might be my tmux config. It is generated by home-manager:
```
# ============================================= #
# Start with defaults from the Sensible plugin  #
# --------------------------------------------- #
run-shell /nix/store/qfc6wwr24a9dgh9kr0ad56gydswf0mnn-tmuxplugin-sensible-unstable-2017-09-05/share/tmux-plugins/sensible/sensible.tmux
# ============================================= #

set  -g default-terminal "tmux-256color"
set  -g base-index      1
setw -g pane-base-index 1





set -g status-keys vi
set -g mode-keys   vi



# rebind main key: C-Space
unbind C-b
set -g prefix C-Space
bind -N "Send the prefix key through to the application" \
  C-Space send-prefix


bind-key -N "Kill the current window" & kill-window
bind-key -N "Kill the current pane" x kill-pane


set  -g mouse             on
setw -g aggressive-resize off
setw -g clock-mode-style  12
set  -s escape-time       0
set  -g history-limit     2000

# ============================================= #
# Load plugins with Home Manager                #
# --------------------------------------------- #

# tmuxplugin-resurrect
# ---------------------
set -g @resurrect-processes 'ssh psql mysql sqlite3'
resurrect_dir=~/.local/share/tmux/resurrect
set -g @resurrect-dir $resurrect_dir
set -g @resurrect-hook-post-save-all "sed -i 's| --cmd .*-vim-pack-dir||g; s|/etc/profiles/per-user/$USER/bin/||g' $(readlink -f $resurrect_dir/last)"

run-shell /nix/store/86z20339qi0bw5291hqbh3sk39n4jwrk-tmuxplugin-resurrect-unstable-2022-05-01/share/tmux-plugins/resurrect/resurrect.tmux


# tmuxplugin-continuum
# ---------------------
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'

run-shell /nix/store/x2kncjmygzfjsrnddmpf05nh9qnrq37n-tmuxplugin-continuum-unstable-2022-01-25/share/tmux-plugins/continuum/continuum.tmux


# tmuxplugin-sessionx
# ---------------------
set -g @sessionx-bind 'o'
set -g @sessionx-window-mode 'on'
set -g @sessionx-zoxide-mode 'on'

run-shell /nix/store/80g36j7a4aqcy13lqff5i7a3zla3m6nx-tmuxplugin-sessionx-dev/share/tmux-plugins/sessionx/sessionx.tmux

# ============================================= #

source-file /nix/store/3dnmglg96320ywkr6ypfcjkh410ijrwd-catppuccin-mocha/base16-catppuccin-mocha.conf

set -sg terminal-overrides ",*:RGB"

unbind r
bind r source-file ~/.config/tmux/tmux.conf
bind-key b set-option status

bind v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key -n C-Left if -F "#{@pane-is-vim}" 'send-keys C-Left' 'select-pane -L'
bind-key -n C-Down if -F "#{@pane-is-vim}" 'send-keys C-Down' 'select-pane -D'
bind-key -n C-Up if -F "#{@pane-is-vim}" 'send-keys C-Up' 'select-pane -U'
bind-key -n C-Right if -F "#{@pane-is-vim}" 'send-keys C-Right' 'select-pane -R'

bind-key -n M-Left if -F "#{@pane-is-vim}" 'send-keys M-Left' 'resize-pane -L 3'
bind-key -n M-Down if -F "#{@pane-is-vim}" 'send-keys M-Down' 'resize-pane -D 3'
bind-key -n M-Up if -F "#{@pane-is-vim}" 'send-keys M-Up' 'resize-pane -U 3'
bind-key -n M-Right if -F "#{@pane-is-vim}" 'send-keys M-Right' 'resize-pane -R 3'
```

### Additional Details and/or Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Mikilio**
Fixes #249

### CODE REVIEW

File: lua/smart-splits/mux/tmux.lua [hunk 1]
```diff
@@ -149,7 +149,7 @@ function M.split_pane(direction, size)
 end
 
 function M.on_init()
-  local pane_id = M.current_pane_id()
+  local pane_id = os.getenv('TMUX_PANE')
```
Comment (mrjones2014) [inline lua/smart-splits/mux/tmux.lua:152]: Environment variables are available via `vim.env`

```suggestion
  local pane_id = vim.env.TMUX_PANE
```

Also do you think this should be used everywhere, or is this just a special case? I'm not a tmux user so I'm not too sure. If you think this will work everywhere instead of `current_pane_id()`, we can remove that function entirely.

Comment (Mikilio) [reply lua/smart-splits/mux/tmux.lua:152]: I actually tried this. But it seems you coded some logic that verifies whether a move has been successful by comparing the active pane to the supposed target. For that we actually want the active pane. So init and exit are the only places where this plays a role.

Comment (mrjones2014) [reply lua/smart-splits/mux/tmux.lua:152]: Ah okay gotcha, that makes sense. This PR looks good then 👍

**Review by mrjones2014 — APPROVED** [review]
